### ISSUE TITLE
Upload library to maven and jitpack

### ISSUE THREAD

**Issue by ashitikov** [trollsoftware/jcomposition#5]

**Comment by rw4lll** [comment]
Jitpack instruction:
1) Add it in your root build.gradle at the end of repositories:
	`
allprojects {
               repositories {
			...
			maven { url 'https://jitpack.io' }
		}
}
`

2) Add the dependency
`
dependencies {
	        compile 'com.github.trollsoftware.jcomposition:processor:1.0'
}
`

**Comment by rw4lll** [comment]
Project was successfully build with this settings.

**Comment by ashitikov** [comment]
@rw4lll, bad description of download section. There should be 2 modules:
1. com.github.trollsoftware.jcomposition:processor:1.0
2. com.github.trollsoftware.jcomposition:api:1.0

Also processor module should be compiled with apt (annotation processor tool) like this:
apt 'com.github.trollsoftware.jcomposition:processor:1.0'.

**Comment by ashitikov** [comment]
@rw4lll, use your fork for development then after feature complete create pull request to main repo.
